# Copyright Rob Gage 2026

[package]
name = "template_project"
version = "0.0.0"
edition = "2024"
license.workspace = true
autobins = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "template-project"
path = "template-project.rs"

[[bin]]
name = "template-project-editor"
path = "template-project-editor.rs"

[dependencies]
editor = { version = "0.0.0", path = "../editor" }
engine = { version = "0.0.0", path = "../engine" }
template_materials = { version = "0.0.0", path = "../template_materials" }
tracing.workspace = true
