# Copyright Rob Gage 2026

[package]
name = "dogwood_template_project"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
autobins = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "template-project"
path = "template-project.rs"

[[bin]]
name = "template-project-editor"
path = "template-project-editor.rs"

[dependencies]
dogwood_editor = { workspace = true }
dogwood_engine = { workspace = true }
dogwood_template_materials = { workspace = true }
tracing.workspace = true
