# Copyright Rob Gage 2026

[package]
name = "dogwood_engine_physics"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
bevy_ecs = { workspace = true }
dogwood_engine_compute = { workspace = true }
dogwood_engine_graphics = { workspace = true }
dogwood_engine_input = { workspace = true }
png.workspace = true
rapier2d = { workspace = true }
tracing.workspace = true
tempfile.workspace = true
wgpu.workspace = true
