# Copyright Rob Gage 2026

[package]
name = "engine_physics"
version = "0.0.0"
edition = "2024"
license.workspace = true

[dependencies]
bevy_ecs = "0.19.1"
engine_compute = { version = "0.0.0", path = "../engine_compute" }
engine_graphics = { version = "0.0.0", path = "../engine_graphics" }
engine_input = { version = "0.0.0", path = "../engine_input" }
rapier2d = { version = "0.35.3", features = ["parallel"] }
tracing.workspace = true
wgpu.workspace = true
