# Copyright Rob Gage 2026

[workspace]
members = ["cli",
    "demo_game",
    "editor",
    "engine",
    "engine_audio",
    "engine_compute",
    "engine_graphics",
    "engine_input",
    "engine_physics",
    "engine_user_interface",
]
resolver = "2"

[workspace.package]
license = "AGPL-3.0-only"

[workspace.dependencies]
egui = "0.36.1"
egui-wgpu = { version = "0.36.1", default-features = false, features = ["winit"] }
egui-winit = { version = "0.36.1", default-features = false }
wgpu = "30.0.0"
pollster = "0.4.0"
