# Copyright Rob Gage 2026

[package]
name = "dogwood_engine_input"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[features]
default = ["x11"]
x11 = ["winit/x11"]
wayland = [
    "winit/wayland",
    "winit/wayland-dlopen",
]

[dependencies]
tracing.workspace = true
winit = { workspace = true }
