# Copyright Rob Gage 2026

[package]
name = "engine_input"
version = "0.0.0"
edition = "2024"
license.workspace = true

[features]
default = ["x11"]
x11 = ["winit/x11"]
wayland = [
    "winit/wayland",
    "winit/wayland-dlopen",
]

[dependencies]
tracing.workspace = true
winit = { version = "0.30.13", default-features = false }
