# Copyright Rob Gage 2026

[package]
name = "engine"
version = "0.0.0"
edition = "2024"

[features]
default = ["x11"]
x11 = ["winit/x11", "engine_user_interface/x11"]
wayland = [
    "winit/wayland",
    "winit/wayland-dlopen",
    "engine_user_interface/wayland",
]

[dependencies]
engine_compute = { version = "0.0.0", path = "../engine_compute" }
engine_physics = { version = "0.0.0", path = "../engine_physics" }
pollster = { workspace = true }
wgpu = { workspace = true }
engine_user_interface = { version = "0.0.0", path = "../engine_user_interface" }
winit = { version = "0.30.13", default-features = false, features = ["rwh_06"] }
