# Copyright Rob Gage 2026

[package]
name = "dogwood_engine"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[features]
default = ["x11"]
x11 = ["winit/x11", "dogwood_engine_user_interface/x11"]
wayland = [
    "winit/wayland",
    "winit/wayland-dlopen",
    "dogwood_engine_user_interface/wayland",
]

[dependencies]
dogwood_engine_compute = { workspace = true }
dogwood_engine_graphics = { workspace = true }
dogwood_engine_input = { workspace = true }
dogwood_engine_physics = { workspace = true }
wgpu = { workspace = true }
egui-wgpu = { workspace = true }
dogwood_engine_user_interface = { workspace = true }
winit = { workspace = true, features = ["rwh_06"] }
egui.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
