# Copyright Rob Gage 2026

[package]
name = "demo_game"
version = "0.0.0"
edition = "2024"
license.workspace = true
autobins = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "demo-game"
path = "demo-game.rs"

[[bin]]
name = "demo-game-editor"
path = "demo-game-editor.rs"

[dependencies]
editor = { version = "0.0.0", path = "../editor" }
engine = { version = "0.0.0", path = "../engine" }
pollster.workspace = true
