// Copyright Rob Gage 2026

use super::Chunk;
use std::error::Error;

/// A `Chunk` and its current streaming state
pub enum ChunkEntry {
    /// A `Chunk` that is ready to be used by the `Scene`
    Active {
        /// The active `Chunk`
        chunk: Chunk,
        /// Whether the `Chunk` has been touched by a simulation process since being loaded or generated
        is_dirty: bool,
    },
    /// `Chunk` is being loaded from `SceneData`
    Loading {
        /// Chunk streaming identifier used to match this `ChunkEntry::Loading` to a loaded chunk
        streaming_identifier: u64,
    },
    /// `Chunk` is being generated by `SceneGenerator`
    Generating {
        /// Chunk streaming identifier used to match this `ChunkEntry::Generating` to a generated chunk
        streaming_identifier: u64,
    },
    /// A dirty `Chunk` being serialized and written outside the fixed tick
    Saving {
        /// Chunk streaming identifier used to match this `ChunkEntry::Saving` to a saved chunk
        streaming_identifier: u64,
    },
    /// Loading or generating the `Chunk` failed
    Error(Box<dyn Error>),
}
