# Copyright Rob Gage 2026

[package]
name = "engine_compute"
version = "0.0.0"
edition = "2024"
license.workspace = true

[dependencies]
pollster = { workspace = true }
tracing = { workspace = true }
wgpu = { workspace = true }

[dev-dependencies]
engine_diagnostics = { version = "0.0.0", path = "../engine_diagnostics" }
