# Copyright Rob Gage 2026

[package]
name = "editor"
version = "0.0.0"
edition = "2024"
license.workspace = true

[dependencies]
engine = { version = "0.0.0", path = "../engine" }
engine_graphics = { version = "0.0.0", path = "../engine_graphics" }
engine_user_interface = { version = "0.0.0", path = "../engine_user_interface" }
engine_compute = { version = "0.0.0", path = "../engine_compute" }
pollster = { workspace = true }
egui.workspace = true
tracing.workspace = true
wgpu = { workspace = true }
winit = { version = "0.30.13", default-features = false, features = ["rwh_06"] }
