// Copyright Rob Gage 2026

use super::SceneChunk;
use std::error::Error;

/// A `SceneChunk` and its current streaming state
pub enum SceneChunkEntry {
    /// A `SceneChunk` that is ready to be used by the `Scene`
    Active {
        /// The active `SceneChunk`
        chunk: SceneChunk,
        /// Whether the `SceneChunk` has been touched by a simulation process since being loaded
        /// or generated
        is_dirty: bool,
    },
    /// `SceneChunk` is being loaded from `SceneData`
    Loading {
        /// Chunk streaming identifier used to match this `ChunkEntry::Loading` to a loaded chunk
        streaming_identifier: u64,
    },
    /// `SceneChunk` is being generated by `SceneGenerator`
    Generating {
        /// Chunk streaming identifier used to match this `ChunkEntry::Generating` to a loaded chunk
        streaming_identifier: u64,
    },
    /// Loading or generating the `SceneChunk` failed
    Error(Box<dyn Error>),
}
