use super::Scene;
use crate::actors::ActorContactEvent;

impl Scene {
    /// Takes actor contact changes generated by the latest fixed updates.
    pub fn drain_actor_contact_events(&mut self) -> Vec<ActorContactEvent> {
        std::mem::take(&mut self.actor_contact_events)
    }
}
