# Copyright Rob Gage 2026

[package]
name = "dogwood_engine_user_interface"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[features]
x11 = ["egui-wgpu/x11", "egui-winit/x11"]
wayland = ["egui-wgpu/wayland", "egui-winit/wayland"]

[dependencies]
egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }
dogwood_engine_graphics = { workspace = true }
tracing.workspace = true
